name: Deploy to Maven Central

env:
  JAVA_VERSION: '17'
  MAVEN_VERSION: '3.6.3'

on:
  release:
    types: [ "released" ]

jobs:
  blackduck:
    name: Blackduck Scan
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Scan With Black Duck
        uses: cap-java/.github/actions/scan-with-blackduck@main
        with:
          blackduck_token: ${{ secrets.BLACK_DUCK_TOKEN }}
          maven-version: ${{ env.MAVEN_VERSION }}
          project-name: com.sap.cds.feature.advanced-event-mesh
          included-modules: cds-feature-advanced-event-mesh
          scan_mode: RAPID # Change to FULL, once there is a project for cds-feature-advanced-event-mesh on sap.blackducksoftware.com
  codeql:
    name: CodeQL Scan
    runs-on: ubuntu-latest
    timeout-minutes: 60
    permissions:
      contents: read
      actions: read
      security-events: write
      packages: read
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Scan With CodeQL
        uses: cap-java/.github/actions/scan-with-codeql@main
        with:
          maven-version: ${{ env.MAVEN_VERSION }}
          java-version: ${{ env.JAVA_VERSION }}
          language: java-kotlin
          queries: security-extended

  #update-version:
  #  name: Update Version
  #  runs-on: ubuntu-latest
  #  steps:
  #    - name: Checkout
  #      uses: actions/checkout@v6
  #      with:
  #        token: ${{ secrets.GH_TOKEN }}
  #    - name: Update version
  #      uses: ./.github/actions/newrelease
  #      with:
  #        java-version: ${{ env.JAVA_VERSION }}
  #        maven-version: ${{ env.MAVEN_VERSION }}
  #    - name: Upload Changed Artifacts
  #      uses: actions/upload-artifact@v7
  #      with:
  #        name: root-new-version
  #        path: .
  #        include-hidden-files: true
  #        retention-days: 1

  requires-approval:
    runs-on: ubuntu-latest
    name: "Waiting for release approval"
    environment: Release-Approval
    permissions:
      contents: read
    steps:
      - name: Approval Step
        run: echo "Release has been approved!"

  build:
    #name: Build and Sonar Scan
    name: Build
    runs-on: ubuntu-latest
    needs: requires-approval
    #needs: update-version
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      #- name: Download artifact
      #  uses: actions/download-artifact@v8
      #  with:
      #    name: root-new-version
      - name: Build
        uses: ./.github/actions/build
        with:
          java-version: ${{ env.JAVA_VERSION }}
          maven-version: ${{ env.MAVEN_VERSION }}
      #- name: Sonar Scan
      #  uses: ./.github/actions/scan-with-sonar
      #  with:
      #    java-version: ${{ env.JAVA_VERSION }}
      #    maven-version: ${{ env.MAVEN_VERSION }}
      #    sonarq-token: ${{ secrets.SONARQ_TOKEN }}
      #    github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload Changed Artifacts
        uses: actions/upload-artifact@v7
        with:
          name: root-build
          include-hidden-files: true
          path: .
          retention-days: 1

  deploy:
    name: Deploy to Maven Central
    runs-on: ubuntu-latest
    environment: Release
    #needs: [blackduck, build]
    needs: [build]
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v8
        with:
          name: root-build
      - name: Deploy
        uses: cap-java/.github/actions/deploy-release@main
        with:
          user: ${{ secrets.CAP_JAVA_CDS_FEATURE_ADVANCED_EVENT_MESH_USER }}
          password: ${{ secrets.CAP_JAVA_CDS_FEATURE_ADVANCED_EVENT_MESH_PASS }}
          gpg-pub-key: ${{ secrets.PGP_PUBKEY_ID_AEM }}
          gpg-private-key: ${{ secrets.PGP_PRIVATE_KEY_AEM }}
          gpg-passphrase: ${{ secrets.PGP_PASSPHRASE_AEM }}
          revision: ${{ github.event.release.tag_name }}
          maven-version: ${{ env.MAVEN_VERSION }}
      - name: Echo Status
        run: echo "The job status is ${{ job.status }}"
