name: Pull Request Voter

env:
  MAVEN_VERSION: '3.6.3'

on:
  workflow_dispatch:
  pull_request:
    branches: [ "main" ]
    types: [reopened, synchronize, opened]

jobs:
  blackduck:
    name: Blackduck Scan
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Scan With Black Duck
        uses: cap-java/.github/actions/scan-with-blackduck@main
        with:
          blackduck_token: ${{ secrets.BLACK_DUCK_TOKEN }}
          maven-version: ${{ env.MAVEN_VERSION }}
          project-name: com.sap.cds.feature.advanced-event-mesh
          included-modules: cds-feature-advanced-event-mesh
          scan_mode: RAPID
          # Use rapid_compare_mode: BOM_COMPARE, once there is a project for cds-feature-advanced-event-mesh on sap.blackducksoftware.com
          #rapid_compare_mode: BOM_COMPARE # PRs might only be blocked by things they introduce, not by pre-existing issues that could have appeared in the main branch in the meantime

  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        java-version: [ 17, 21 ]

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Build
        uses: ./.github/actions/build
        with:
          java-version: ${{ matrix.java-version }}
          maven-version: ${{ env.MAVEN_VERSION }}

      #- name: SonarQube Scan
      #  uses: ./.github/actions/scan-with-sonar
      #  if: ${{ matrix.java-version == 17 }}
      #  with:
      #    java-version: ${{ matrix.java-version }}
      #    maven-version: ${{ env.MAVEN_VERSION }}
      #    sonarq-token: ${{ secrets.SONARQ_TOKEN }}
      #    github-token: ${{ secrets.GITHUB_TOKEN }}
